### ISSUE TITLE
AR Approvals

### ISSUE THREAD

**Issue by PatricePascual-ACF** [HHS/Head-Start-TTADP#104]

**Comment by PatricePascual-ACF** [comment]
User story: Approval (and status)
As a TTA manager(s) responsible for reivewing and approving a submitted activity report, I want to 
1) receive notice that the report needs my review; 
2) approve as is; 
3) make my own edits(?); 
4) request revisions; 
5) review the revisions made and mark "Approved".

**Comment by pamlo412** [comment]
Closing this issue as a duplicate of #109. I moved the proposed AC above to 109.
