### ISSUE TITLE
Implement scans in CI/CD pipeline to meet QASP requirements

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#11]
In order to be compliant with the QASP, the CI pipeline should implement the following checks and scans

* code coverage, both backend and frontend code
* linting, both backend and frontend code (ad hoc's choice for style guide/linter, though document why)
* static security scans such as `yarn audit`
* dynamic security scan(s) such as [OWASP Zap](https://www.zaproxy.org/)

Example pipeline from prototype app: https://github.com/18F/Head-Start-TTA/blob/main/.circleci/config.yml

That pipeline includes:

* tests (rspec)
* linting (standard ruby)
* static code analysis (brakeman)
* dependency scans (bundler audit & yarn audit)
 

Acceptance Criteria:

1) scans are implemented in CI pipeline and passing.

---

For this ticket:
- [x] CI pipeline static security scans such as `yarn audit` - completed by AH fork PR https://github.com/adhocteam/Head-Start-TTADP/pull/37, HHS PR https://github.com/HHS/Head-Start-TTADP/pull/68
- [x] fail CI pipeline if code coverage (for both backend or frontend) falls below certain percentage - completed by AH fork PR https://github.com/adhocteam/Head-Start-TTADP/pull/37, HHS PR https://github.com/HHS/Head-Start-TTADP/pull/68
- [ ] CI pipeline dynamic security scan(s) such as [OWASP Zap](https://www.zaproxy.org/) - completed by AH fork PR https://github.com/adhocteam/Head-Start-TTADP/pull/44, HHS PR https://github.com/HHS/Head-Start-TTADP/pull/94
- [ ] add ADR for linting, static scan, and dynamic scan tech choices (linting was implemented on CI in https://github.com/adhocteam/Head-Start-TTADP/pull/9 in pursuit of https://github.com/HHS/Head-Start-TTADP/issues/12) - completed by AH fork PR https://github.com/adhocteam/Head-Start-TTADP/pull/44, HHS PR https://github.com/HHS/Head-Start-TTADP/pull/94

**Comment by rahearn** [comment]
[Definition of Done](https://github.com/HHS/Head-Start-TTADP/wiki/Definition-of-Done)

- [ ] CI pipeline green
- [ ] Code is meaningfully tested
- [ ] No linting errors or warnings
- [ ] UI meets WCAG 2.1 - Levels A and AA
- [ ] Security scans have passed
- [ ] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions.

**Comment by SarahJaine** [comment]
@rahearn Did you want a formal ADR for our linter choice, or is explaining it in the PR sufficient?

**Comment by rahearn** [comment]
> formal ADR for our linter choice

Yeah, I think it'd be good to document why each linter and scanner was chosen. I'm open to a single ADR that combines all the scanner choices though if that seems better/easier/cleaner.

**Comment by SarahJaine** [comment]
@rahearn Josh and I finally got the OWASP ZAP to run on CI. Here's an [example of the circle ci run](https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP/331/workflows/dfc090ee-541c-4893-8b00-50d9b7df01d6/jobs/1105). As you can see it fails (non-zero exit status return) for all warnings. The default configuration is for ZAP to mark all vulnerabilities as WARN- but we can specify a config file which can change any rules to FAIL or IGNORE. I was thinking we'd create a custom config and use it to take advantage of the native exit codes the script returns (0 = no issues, 1 = any failures, 2 = only warnings) and interpret only exit code 1 as a true pipeline failure. _**My question is this, did you already have in mind a set of rules that should be FAIL or IGNORE instead of WARN?**_

**Comment by rahearn** [comment]
> interpret only exit code 1 as a true pipeline failure

That sounds good to me. Similar to the audit results I'd prefer WARNs to be output to view, but they should not block the build.

I did not have any customizations in mind from what zap does by default.

**Comment by SarahJaine** [comment]
@rahearn The default config is for everything to be a WARN.  If we have the pipeline fail only for FAILs, it will never fail.  That's okay?

**Comment by rahearn** [comment]
> default config is for everything to be a WARN

oh, no, that's no good. I'll take a look at what I've done in the past on Monday
