### ISSUE TITLE
Automated deployment via CI/CD pipeline

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#12]
After successful passing of the CI pipeline, certain branches should automatically deploy to cloud.gov environments.

TBD: which branches (from which forks) deploy where.

CI Needs
- [x] Build fails on test and linting errors https://github.com/adhocteam/Head-Start-TTADP/pull/9
- [x] Display test results https://github.com/adhocteam/Head-Start-TTADP/pull/15
- [x] Store coverage reports https://github.com/adhocteam/Head-Start-TTADP/pull/15
- [n/a] Build fails below certain coverage threshold - moved to https://github.com/HHS/Head-Start-TTADP/issues/11
- [n/a] Build fails if security vulnerabilities found - moved to https://github.com/HHS/Head-Start-TTADP/issues/11
- [x] bonus: cache node modules https://github.com/adhocteam/Head-Start-TTADP/pull/21https://github.com/adhocteam/Head-Start-TTADP/pull/21

CD Needs
- [x] Deploy to dev - https://github.com/adhocteam/Head-Start-TTADP/pull/23, evidenced in https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP/230/workflows/6b5cf689-4975-4e07-b9cf-054a9e4ff23b
- [ ] Deploy to staging - https://github.com/HHS/Head-Start-TTADP/pull/46
- [ ] Deploy to production

**Comment by pamlo412** [comment]
Moving this story to Sprint 1 for completion.
