### ISSUE TITLE
URLs not properly routed in deployed environments

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#121]
Found while reviewing #120. Navigating directly to a deep link such as https://tta-smarthub-dev.app.cloud.gov/activity-reports does not work. It does work on localhost, so there's a dev/production routing difference in play.

**Comment by pamlo412** [comment]
@rahearn For prioritization purposes with @PatricePascual-ACF, I just want to confirm that the use case(s) affected by this bug. I assume this is one: If a user clicks a bookmarked link to a specific Activity Report, they won't be taken to that report.

**Comment by rahearn** [comment]
> If a user clicks a bookmarked link to a specific Activity Report, they won't be taken to that report.

Correct
