### ISSUE TITLE
As a user, I want uploaded files to be scanned for malicious code, so that I don't have to call the IT department (RA-05, SI-03)

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#123]
**Task:**
Files uploaded to s3 should be scanned for malicious code to keep our users safe.

**Possible solutions:** 
a ClamAV [sidecar buildpack](https://docs.cloudfoundry.org/buildpacks/sidecar-buildpacks.html).

**Exclusions:**
- ability to upload the files, #99 
- buckets for uploaded files, #149

**Comment by pamlo412** [comment]
@rahearn I assigned this issue to the V1.0 MVP milestone on the assumption that it's needed for ATO.

**Comment by rahearn** [comment]
The files can be scanned either while residing in s3, or as they pass through the server, whichever makes more sense for the overall implementation.

**Comment by rahearn** [comment]
If a sidecar buildpack is used, then #55 is either a prerequisite or should be done at the same time.

**Comment by rahearn** [comment]
Spike complete, work tracked by #203
