### ISSUE TITLE
Process decision: What format of Architectural Decision Record should be used.

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#13]
[Architectural Design Records](https://adr.github.io/) are a format for documenting significant architectural changes and decisions. Documenting our decisions here will help streamline the ATO process by letting our design documents point to our ADRs, and will enhance new-engineer understanding of the code by keeping those decisions alongside the code.

Additionally, ADRs make good output of investigatory spikes, before the actual implementation is done.

There are several flavors of how to write them up, and I would like the team to decide on a common format for them.

**Comment by rahearn** [comment]
We'll update https://github.com/HHS/Head-Start-TTADP/wiki/Definition-of-Done with the decision that's made

**Comment by kryswisnaskas** [comment]
We thought Nygard format would work. Thanks.

**Comment by rahearn** [comment]
Thanks, DoD wiki has been updated.
