### ISSUE TITLE
Implement API error handling

### ISSUE THREAD

**Issue by kryswisnaskas** [HHS/Head-Start-TTADP#134]
Implement API error handling so that the errors are stored in a database. This will allow a better view into any API errors encountered during the application use.

Acceptance criteria:

- [ ] Model and migrations are created for the db table to store errors. 
- [ ] Any API errors are sent to that table

**Comment by rahearn** [comment]
Definition of Done

- [x] The business and/or user value of a story has been met
- [x] CI pipeline green
- [x] Code is meaningfully tested
- [x] No linting errors or warnings
- [x] Code has deployed to a staging environment
- [x] Security scans have passed
