### ISSUE TITLE
Request Permissions Page

### ISSUE THREAD

**Issue by PatricePascual-ACF** [HHS/Head-Start-TTADP#139]
**User story:**
As a new TTA user logging in for the first time, I want to request permission to access the TTA Hub so that I can use the features. 

**Acceptance criteria:**
- [ ] The "request permission" button should go to this SmartSheet form: https://app.smartsheetgov.com/b/form/f0b4725683f04f349a939bd2e3f5425a
- [ ] This applies to users who lost access or anyone who doesn't have site access permission

**Link to design**
@arickalewis1 - I don't think we need the copy below "Request Permission"?
Also, the SS form would also be where people report tech issues. Is there a pop-up for that? 
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/135562661/simulate/sitemap

**Comment by pamlo412** [comment]
@kryswisnaskas when you're back, I want your input on these 2 stories we discussed at grooming.

**Comment by arickalewis1** [comment]
Is the TBD content accessible for this issue? @PatricePascual-ACF @marriej

**Comment by arickalewis1** [comment]
This should show up after they log in for the first time, correct? @marriej @kryswisnaskas

**Comment by kryswisnaskas** [comment]
> This should show up after they log in for the first time, correct?

Yes, that's right. @arickalewis1

**Comment by dcloud** [comment]
To describe this another way, this page is for when a user has authenticated (through HSES) but doesn't have any permissions/roles to do anything. This page is within the authenticated routes, but other authenticated routes wouldn't be available to the permissionless user (or we would redirect them).

**Comment by dcloud** [comment]
Looking at the "Scopes" table, users will need to have the `SITE_ACCESS` permission to log in, so will need a check that user has only that permission.
