### ISSUE TITLE
Button to create Activity Report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#146]
**User story:**
As a TTA specialist, I want an easy-to-find option to create a new Activity Report so that I can quickly record initial information about an activity.

**Acceptance criteria:**
- [ ] users can select an option (e.g. a button) on the Home page to create a new activity report 
- [ ] selecting the option launches the activity report form and section navigation menu

**Exclusions:**
- saving the new report - #98 
- generating an ID for the new report - #145

**Comment by rahearn** [comment]
This feels like a duplicate of #153

**Comment by pamlo412** [comment]
Oops - thanks @rahearn. Closing this issue as a duplicate of #153
