### ISSUE TITLE
Add application logging

### ISSUE THREAD

**Issue by kryswisnaskas** [HHS/Head-Start-TTADP#15]
Logging should be configured and implemented.

Definition of Done:

- [ ] Logging is implemented with multiple levels.
- [ ] Architectural Decision Records are written for major infrastructure decisions.

**Comment by rahearn** [comment]
I don't know if it belongs on this story, or another, but for some things we will likely need an audit logging capability.

We'll need to be able to track who made changes and when, especially around security-sensitive things like authorization roles.

**Comment by kryswisnaskas** [comment]
An audit logging capability sounds like a separate story/issue. Thanks for flagging it here though.
