### ISSUE TITLE
Assigning IDs to goals 

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#151]
**User story:**
As a TTA specialist referencing my work in time reports and other contexts, I want goals to each have their own ID that I can reference so that I don't have to waste time naming or describing the goal.

**Acceptance criteria:**
- [ ] the system generates and stores a goal ID 
- [ ] the system can display the report ID in the UI  **NEEDS RESEARCH and DESIGN**
- [ ] each goal ID is unique, including Smartsheet goal IDs generated before the Smart Hub go live 
     - [ ] implementation option: handle this need by starting the Smart Hub numbering high enough that we don't generate duplicate IDs

**Dependencies:**
- saving the report #98 
- create the activity report

**Exclusions:**
- displaying the ID in the report and on the Home page, story TBD

**Comment by PatricePascual-ACF** [comment]
Hi @pamlo412. This one needs research and is not ready for grooming. I will speak with Damon but I also question if it's an MVP feature.  
The practice of and format for assigning goal IDs is not standard across regions. Even assigning an ordinal count, for example,  could be misinterpreted as reflecting the goal's  imporance to the grantee or to the region, and that's probably highly subjective.

**Comment by pamlo412** [comment]
Thanks @PatricePascual-ACF for your input - I'm moving this one to our Post MVP bucket (a label that we can query) for future consideration. We can and should review that bucket once a week going forward. I'll put the query link in Slack.

**Comment by pamlo412** [comment]
Closing this issue. I've moved it over to Jira for consideration after the MVP release: https://ocio-jira.acf.hhs.gov/browse/TTASH-5.
