### ISSUE TITLE
Prefilter Grantee names and Grant IDs based on region

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#154]
**User story:**
As a regional TTA specialist completing an Activity Report, I want the grantee names and grant IDs that display as selectable to be prefiltered based on my region so that I can easily find the ones I need and not be overwhelmed by a long list.

**Acceptance criteria:**
- [ ] when a user opens the dropdown to select Grantee names and associated Grant IDs, the list of available options is filtered to include only those names and IDs associated with the report's region ( user's region) .

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880468

**Exclusions:**
- A specialist is arranging a "cluster" activity (which is an activity that brings multiple grantees together for an activity) wants the option to select a grantee outside of their region from a list of all grantees. For the MVP, the specialist will need to request the grantee be added, which is why we have the content indicated in the AC 
- filtering non-grantee list based on region: not necessary because this list is the same across regions

**Comment by pamlo412** [comment]
This story is ready for team grooming.

**Comment by pamlo412** [comment]
Discussed this story at standup grooming today. The AC and exclusions are now well understood, but we will wait to point this one after the design is updated to reflect the AC.

**Comment by PatricePascual-ACF** [comment]
@marriej - I think we keep this one and delete 162? https://github.com/HHS/Head-Start-TTADP/issues/162?
