### ISSUE TITLE
DUPLICATE: Validation of fields in the Activity Reports

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#158]
**User story:**
As a TTA specialist completing an Activity Report, I want the Smart Hub to ensure that I complete all required fields before submitting the report for approval, so as to reduce the revision requests my manager needs to make.

**Acceptance criteria:**

- [ ] Fields marked as required in the design are validated upon report submission https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880468/simulate/sitemap
- [ ] Error message upon submission and within the section with the error.
"Please complete all required fields." 

Questions:
Double check accessibility requirements around alerting.

**Comment by PatricePascual-ACF** [comment]
@marriej - this one

**Comment by marriej** [comment]
@PatricePascual-ACF please provide content for error.

**Comment by PatricePascual-ACF** [comment]
> @PatricePascual-ACF please provide content for error.

Added: "Please complete all required fields." 
(I think that will suffice, since they are in the seciton with missing info. Agree, @arickalewis1?)

**Comment by arickalewis1** [comment]
@PatricePascual-ACF this is what I have so far.

**Submit page**
<img width="1007" alt="Screen Shot 2021-01-28 at 10 21 47 AM" src="https://user-images.githubusercontent.com/54509359/106168060-7a7b1a80-6153-11eb-9410-f221a155f951.png">

**Specific section with missing information.**
<img width="550" alt="Screen Shot 2021-01-28 at 10 27 35 AM" src="https://user-images.githubusercontent.com/54509359/106168089-84048280-6153-11eb-99a1-eb7f1d16bef1.png">

**Comment by rahearn** [comment]
Closing as duplicate.
