### ISSUE TITLE
Create a database, models and migrations

### ISSUE THREAD

**Issue by kryswisnaskas** [HHS/Head-Start-TTADP#16]
Definition of Done:

- [x] An initial database is schema is designed.
- [x] Database models are created based on the schema.
- [x] Migrations are created.
- [x] Code is meaningfully tested
- [x] Architectural Decision Records are written for major infrastructure decisions.

**Comment by kryswisnaskas** [comment]
Notes - This spike started as a more complete database schema, but in the absence of user facing stories turned into a limited subset consisting of one table (User table) being created. The value of this spike in setting up the infrastructure/foundation to be able to build on top.

**Comment by rahearn** [comment]
Closed as part of #40
