### ISSUE TITLE
Display Grantee Names and Grant Numbers pulled from database

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#163]
**User story:**
As a TTA Specialist completing an Activity Report, I want the grantee names and associated grant numbers for my region to display in the grantee dropdown so that I can quickly find and select the grantee(s) with whom I worked on an activity.

**Acceptance criteria:**
- [x] when the user selects the Grantee radio button option,  the values that display in the "Who is this activity for?" field are the combined Grantee name + Grant number options pulled from our database (and originally from HSES).

**Design:** 
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880468/simulate/sitemap
(Aricka updated to show realistic grant numbers combined with grantee name in one line include example with 2 lines of text. Grant number example: 05CH09845)

**Exclusions:**
~- displaying non-grantee options pulled from database #164~
~- selecting multiple grantees or non-grantees in one report #166~
~- type-ahead in dropdown (for faster searching + selecting) #165~

**Comment by pamlo412** [comment]
Added link to the now updated design.

**Comment by kryswisnaskas** [comment]
Assigning to @jasalisbury since it's a part of saving of the activity report.
