### ISSUE TITLE
Enable type-ahead searching of grantees and non-grantees

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#165]
**User story:**
As a TTA Specialist completing an Activity Report, I want to be able to start typing the name of a grantee or non-grantee in the "Who is this activity for?" dropdown so that I can find and select it faster.

**Acceptance criteria:**
- [ ] when a user starts typing letters into the "Who is this activity for?" dropdown, the list filters to show matching options.

**Assumptions:**
- we don't need separate stories for type-ahead on grantees and non-grantees because the capability need only be implemented once to work on both lists
- implementing type-ahead for the non-grantee options doesn't have as much UX impact because that list is short enough to view all options at once; but it still has value in making type-ahead consistently available as a way to search and select via your keyboard (i.e. it's good for accessibility)

**Exclusions:**
- pulling the non-grantee options from the database #164 
- pulling the grantee names and grant IDs from the database #163
- selecting multiple grantees or non-grantees #166

**Comment by rahearn** [comment]
This should already be taken care of via #128 (typing filters list in the multiselect) and #163 and #164 (populating the options in the first place)

**Comment by pamlo412** [comment]
Closing per discussion at grooming
