### ISSUE TITLE
Select multiple grantees or non-grantees for one activity report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#166]
**User story:**
As a TTA Specialist completing an Activity Report, I want to be able to select more than one grantee or non-grantee for inclusion in my report so that I can accurately and expediently report on an activity that helped more than one grantee or concerned more than one non-grantee activity.

**Acceptance criteria:**
- [ ] the user can select and enter more than one grantee or non-grantee in the "Who is this activity for? dropdown.

**Exclusions:**
- pulling the grantee names and grant IDs from the database. #163 
- pulling the non-grantee options from the database #164 
- type-ahead in the dropdown #165 
- selecting both a grantee and a non-grantee for one report - not needed

**Comment by rahearn** [comment]
This should already be taken care of via #128 (multiselect enabled selecting multiple options) and #163 and #164 (populating the options in the first place)

**Comment by pamlo412** [comment]
Closing per discussion at grooming
