### ISSUE TITLE
Capture reasons for a TTA activity

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#171]
**User story:**
As a TTA Specialist completing an activity report, I want to select from predefined reasons for the activity so that activities can be compared based on discrete reasons.

**Acceptance criteria:**
- [x] the user can select multiple predefined reasons: (This list of Reasons is the "source of truth." - Patrice)
Below Competitive Threshold (CLASS)
Below Quality Threshold (CLASS)
Change in Scope
Full Enrollment
New Grantee
New Director or Management
New Program Option
New Staff / Turnover
Ongoing Quality Improvement
Planning/Coordination (also TTA Plan Agreement)
School Readiness Goals
Monitoring | Area of Concern
Monitoring | Noncompliance
Monitoring | Deficiency

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880468

**Comment by pamlo412** [comment]
@PatricePascual-ACF - this story needs the list of reasons for grantees and regional office

**Comment by PatricePascual-ACF** [comment]
Hi, @pamlo412 - I added the Reason values.

**Comment by pamlo412** [comment]
Hi @PatricePascual-ACF - something went wrong - I don't see the reasons you added. Can you take another look? Thank you!
