### ISSUE TITLE
Bug: Help popup for calendar is confusing

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#175]
When you click the calendar in the Activity Summary section of an Activity Report, there's a question mark in the bottom right corner of the popup. If you click it, it displays help about shortcuts that don't work (at least not for me). 

Tagging @arickalewis1 for a judgment call.

**Comment by arickalewis1** [comment]
Had a short conversation with Josh. The shortcut works for him:

"when "?" is pressed it is included in the library we use but we can remove it if we need to"
![Screenshot from 2020-12-18 10-06-52](https://user-images.githubusercontent.com/54509359/102635527-11969080-4119-11eb-89b0-9378287812a4.png)

**Comment by gopar** [comment]
Was there a final conclusion for this? Will the shortcuts be removed?

If shortcuts will not be removed, then we would need more information to fix this:
1. Would you happen to have any browser plugins that could be interfering?
2. Does this happen when trying with different browser(s)? 
4. What browser and browser version are you using?
5. What OS are you using? (Windows/Mac)

**Comment by marriej** [comment]
@gopar can we remove them?

**Comment by gopar** [comment]
Yeah, we can. I can push out a PR for this
