### ISSUE TITLE
View activity reports

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#188]
**User story:**
As a TTA Smart Hub user, I want to have appropriate permissions to reports when I open them, so I can do the work I need to do.

**Acceptance criteria:**
- [ ] if a user clicks/selects a report in the "all reports" list on the post-login landing page, the individual report opens with the view-only mode

**Exclusions:**
- print-friendly styles for the view-only mode for approved reports: #108 
- all-report list on the landing page: #5

**Comment by pamlo412** [comment]
Ready for grooming with the team.

**Comment by jasalisbury** [comment]
@rahearn @marriej I think this ticket can be closed

**Comment by kryswisnaskas** [comment]
Agree, this is already implemented.

**Comment by rahearn** [comment]
Closing, this has been done.
