### ISSUE TITLE
Epic 0: Sprint 0 setup/startup work

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#20]
This epic covers all work in Sprint 0--hello-world app, dev setup, design frameworks, the user research plan, the initial creation of sprint backlogs, and any other work that is startup work and not yet user-facing.

Issues under this epic:
#3 Review and confirm the info architecture for activity reports in the MVP
#9 Hello world app
#10 Create a user research plan for the MVP
#11 Implement scans in CI/CD pipeline to meet QASP requirements
#12 Automated deployment via CI/CD pipeline
#15 Implement logging in ttadp
#16 Create a database, models, and migrations
#17 Add uswds to the frontend
#18 Add routing to the frontend 
#21 Create a framework for design
#22 Create initial backlog of ready user stories
#23 Create persistent infrastructure

**Comment by rahearn** [comment]
Closing out sprint 0
