### ISSUE TITLE
Training Plan

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#200]
https://docs.google.com/document/d/10lhmFHtxZbxsd0cS77KYbytEhvAHZCL1/edit

**Comment by rahearn** [comment]
@pamlo412 & @PatricePascual-ACF Section 4.3 of this document has schedule dates in the past, can you each update the status and/or dates in that table?

**Comment by pamlo412** [comment]
@rahearn I suggest that Jan 8,  2021 aligns with our new MVP timeline and updated the document accordingly. We may tweak the dates one more time this week when we have a chance to review them with @PatricePascual-ACF.

**Comment by PatricePascual-ACF** [comment]
@rahearn @pamlo412 
I don't want to send the wrong message about staying on the current ATO schedule, but my inclination is to deliver closer to launch. How do you feel about this? 
Prepare evaluation: Jan. 15
Prepare scripts: Jan. 15
Coodinate/Send invitations: Jan 25
Deliver training: Feb. 9

**Comment by rahearn** [comment]
> my inclination is to deliver closer to launch

I think having the full plan (even if not the full curriculum) is important pre-ato, but actually delivering said training post ato/pre launch is completely fine
