### ISSUE TITLE
As a user,  I want my uploaded files scanned asynchronously, so that my activity report upload is performant (RA-5)

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#204]
This story builds on #150 and #203

Files uploaded in #150 should trigger a background process to retrieve those files from s3, pass them to the API created by #203, and update their status with the scan results.

**Comment by rahearn** [comment]
ClamAV api server is available to sandbox, dev, and staging accounts at `http://clamapi-ttahub-dev.apps.internal:8080`

**Comment by rahearn** [comment]
An example curl command that will trigger a file scan is `curl -F "name=test" -F "@./path/to/file.txt" clamapi-ttahub-dev.apps.internal:8080/scan`

**Comment by dcmcand** [comment]
Do we have any capacity concerns here? Like is it ok just to call the api when each file is uploaded initially, or do we need to look at implementing a queue to keep clamav from being hammered? Just doing an async call to the api and updating the status with the results seems far simpler, I just don't want to drown the clamav server if 500 people all decide to upload 10 documents at the same time.

**Comment by dcmcand** [comment]
Also, if something does come back as unsafe, do we delete the file from s3?

**Comment by rahearn** [comment]
The clamav setup is here: https://github.com/HHS/Head-Start-clamav-api-cg-app and can be run locally

**Comment by rahearn** [comment]
> Do we have any capacity concerns here

So, this is a bit more of a concern than I originally thought. I think a basic retry system is still probably fine, but we definitely want to ensure that any failures/retries are added to the audit log so we can keep an eye on things.
