### ISSUE TITLE
As a system administrator, I want to import topics from the overall topic sheet so that I have the full current list in the system

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#207]
Source smartsheet link to come

**Comment by kryswisnaskas** [comment]
@rahearn Just checking on this whether still something we need and if there is a link. Thanks.

**Comment by PatricePascual-ACF** [comment]
@kryswisnaskas @rahearn I pasted the topic list in 235 - do we still need this story?
https://github.com/HHS/Head-Start-TTADP/issues/235

**Comment by rahearn** [comment]
No, I think we can remove this. Any future topics stories should focus on maintaining the list in the smarthub, not maintaining in smartsheet and syncing from there
