### ISSUE TITLE
As a system administrator, I want to handle multiple topics formats and regions

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#208]
Builds on https://github.com/HHS/Head-Start-TTADP/pull/205. We need to support:

1) Topics column may be of form `Topic name | RoleAcronym[, RoleAcronym]` or just `Topic name`
2) Multiple regions need to be imported, each from their own smartsheet, so the script should handle being called multiple times (once for each region)

**Comment by rahearn** [comment]
Region 9 has changed "Goal..." to be "Anticipated Outcome...". We need to support both of those column formats.

@PatricePascual-ACF we also need to check the rest of the regions for any deviations, and ideally ask the regions to not make any (more) changes.

**Comment by PatricePascual-ACF** [comment]
@rahearn  I want to require regions to change any column names back before we export data.  
In other words, R9  will go back to Goal.  Confirming w/ Damon now.
