### ISSUE TITLE
As a user navigating by keyboard, I want focus to be applied to the header of a Activity Report step after navigating via the stepper

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#212]
There is a nice "skip to form content" link on the first step, but after that you must tab through the entire stepper after navigating.

**Comment by dcmcand** [comment]
@rahearn just to clarify, you're saying when I navigate to Topics and Resources (for example) focus should be on the topics and resources header correct?

**Comment by rahearn** [comment]
> you're saying when I navigate to Topics and Resources (for example) focus should be on the topics and resources header

Yes. And the "after navigating via the stepper" part might be a red herring. Verify that when you navigate via "Save & Continue" the focus is up at the top of the next screen as well.
