### ISSUE TITLE
Pull all Smartsheet Activity Report data into Hub database

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#215]
**User story:**
As a TTA Smart Hub user transitioning from Smartsheet Activity Reports to the Smart Hub, I want all the data entered in my SS ARs from Sept 2020 to be available in the Hub so that my current work continues seamlessly.

**Acceptance Criteria:**
- "Learning level" data gets imported to database. will not be displayed in the AR.
- 
**Exclusions:**
- Goals from smartsheets ARs are not being imported into the goals dropdown.
- Goals will be imported as part of the old ARs.

**Notes:**
- this is a one-time pull. SS AR users will be advised that they shouldn't use SS ARs after the Hub go live.

**Comment by dcloud** [comment]
## Notes mar 3, 2021

I took an initial look at the data coming out of smart sheets by exporting the 'R* Activity Reports' workbooks as Excel files and doing some inspection on the data. 

I inspected the headers and saw that there were variations in number and naming of headers across sheets. Some variations were minor, but there were other columns that seemed to exist only in certain sheets. I'll need to create a list of those to look into, but for example `Non-Grantee (CHECK)` appears in the _R1_ sheet, and not others. I counted at least 59 unique headers across 9 of the 12 reports (hadn't yet downloaded 10-12), where each report had between 44-46 named columns.

Another thing I noticed was that multi-value cells, e.g. 'Grantee Name', seemed to separate values with a newline, which is a good thing to know, but wasn't obvious when opening the files in Excel.

**Comment by dcloud** [comment]
## Notes Mar 5, 2021

Reviewed column name discrepancies and those will be mitigated in smart sheets. The import script will still attempt to normalize field names for better mapping to data models.

Also, there are **R14** records in sheets R5, R9, R10 and R11. Those records are low in the key sequence (`R14-AR-000031` in R5 sheet appears to have the highest numeric suffix value). The numbers don't overlap with those of the proper R* ids, so we can replace R14 with the actual region id during import.

**Comment by dcloud** [comment]
Noting that data model changes introduced via adhocteam#205 block completion of this issue.

**Comment by dcloud** [comment]
### TODO LIST

- Smartsheet has file attachments, so the exported Excel files are not the full picture
  - How/when to get file attachments moved over
  - Are there other pieces of data that are not "inside" the sheets?
- The aforementioned data model changes to a few "resources" fields
- Considering how data that should come from HSES plays into this import (e.g. Grantee name/ids)
- Confirming field mappings and addressing any extra fields
