### ISSUE TITLE
Display selected or created goals in the Activity Report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#216]
**User story:**
As a TTA specialist creating an activity report, I want to see the goals that have been added to the report so that I can easily review them. 

**Acceptance Criteria:**
- [x] In the Goals and Objectives section of an Activity Report, the user can see the list of goals that have been entered in the report

~the more recent goals display on top~ do this as part of #117

**Exclusions:**
- selecting goals from TTA Plan Smartsheets: #117 
- selecting goals entered in SmartSheet Activity Reports #214 
- handling the anticipated increase in the length of this list (post MVP) #217

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880471/simulate/sitemap

**Engineering Notes**
- just the more complex FE display with the selected goals
- does not include the trash/remove icon
- does not include "add new objective"

**Comment by kryswisnaskas** [comment]
> the source of the goal (TTA Plan or previous AR) displays

Looks like we have 2 sources for the goals. Is that correct?

**Comment by pamlo412** [comment]
@kryswisnaskas groomed this today with the team in your absence. Assigning to you to point with them.

**Comment by pamlo412** [comment]
> > the source of the goal (TTA Plan or previous AR) displays
> 
> Looks like we have 2 sources for the goals. Is that correct?

@kryswisnaskas yes - the TTA Plan and previous Activity Reports. You could say 3 sources, if you count creating a new goal in the current AR.
