### ISSUE TITLE
Removing a goal from an AR in draft status

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#219]
**User story:**
As a TTA specialist creating an Activity Report, I want to remove a goal that I (or one of my collaborators) added to a draft AR by mistake so that the report will be accurate. 

**Acceptance Criteria:**
- [ ] an author or collaborator of a report can remove a goal from an AR that is still in draft status. 

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880471/simulate/sitemap

**Exclusions:**
- assigned approvers of a report can't remove a goal, they can only request its removal per #138  
- deletion of goal from database #220

**Comment by pamlo412** [comment]
@kryswisnaskas We groomed this today in your absence. Assigning to you to point with the team.

**Comment by kryswisnaskas** [comment]
@pamlo412 , @marriej 

To clarify the AC.

> an author or collaborator of a report can remove a goal from the report as long as the report has not yet been approved

With multiple managers, should we say "by at least one approver" or "all of the approvers"?

**Comment by pamlo412** [comment]
@kryswisnaskas Good catch - I can imagine a scenario in which the second approver (TTAC) wants the goal removed and the first approver (EC Mgr) agrees even though they thought it was fine when they approved. But we need @PatricePascual-ACF to make this call.

**Comment by jasalisbury** [comment]
@marriej Just to clarify we want users to be able to remove goals as long as the report has not been submitted to a manager for approval?
