### ISSUE TITLE
Create persistent infrastructure

### ISSUE THREAD

**Issue by SarahJaine** [HHS/Head-Start-TTADP#23]
Create way to initialize persistent Infrastructure (e.g. infrastructure that is not created for each application deployment.)

Definition of done:
- [x] at least one service is deployed to cloud.gov dev space

**Comment by pamlo412** [comment]
Moved this story from sprint 1 to sprint 2.

**Comment by SarahJaine** [comment]
Moving this conversation about database plans from slack to the gh.
@rahearn I’m a little concerned about using the shared plan for dev and staging rds instances. The shared plan uses postgres v9.5.15. Any non-shared plan (which we would use for prod)will automagically get the latest aws postgres, v12.4. CircleCI is running tests against v12.4. With this setup, it’s possible that we’re passing tests (in CircleCI postgres v12.4) for a postgres technology that may fail when deployed to dev/staging (postgres v9.5) but work well in prod (postgres v12.4). The early/invalid fail in dev/staging isn’t necessarily that detrimental, and I'm glad prod and circleci mathc, but we really won’t be able to take advantage of any features that exist in v10-12. I’m not sure these would be features we’re going to use anyway, but it bares keeping in mind. Do you have thoughts on this?

**Comment by rahearn** [comment]
> The shared plan uses postgres v9.5.15.

I didn't realize shared was that far behind. OK, let's go with the dedicated instances across the board. Does starting with `micro-psql` sound ok to you?

**Comment by SarahJaine** [comment]
That's great @rahearn, I'm happy to use micro for dev and staging. I was thinking more about prod and I'm noticing in the [clould.gov rds docs](https://cloud.gov/docs/services/relational-database/) they don't actually tell us what instance type each plan is using. I'm assuming they're either using T2 or T3-- is there a way for us to discover which? I’d be more comfortable with a small instance if it were T3 rather than T2 because T3 has 2vCPU at the small size while T2 small only has 1vCPU. The memory is the same for T2/T3 (2 small, 4 medium).

**Comment by rahearn** [comment]
> don't actually tell us what instance type each plan is using

Got a breakdown from cloud.gov support. For the PostgreSQL plans:

* the medium "higher workload" plan is `m3`
* the large & xlarge "higher workload" plan is `m4`
* all others are `t3`

**Comment by SarahJaine** [comment]
@rahearn Were you able to apply the changes to staging? I just went to check and then remembered I can't see the `ttahub-staging` space in cloud.gov.

**Comment by rahearn** [comment]
Terraform applied to staging

```
ryancahearn@TCOH2J-K1N5HV2F ~/s/h/H/t/staging (main=)> terraform apply
data.cloudfoundry_service.rds: Refreshing state...
data.cloudfoundry_space.space: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudfoundry_service_instance.database will be created
  + resource "cloudfoundry_service_instance" "database" {
      + id               = (known after apply)
      + name             = "ttahub-staging"
      + recursive_delete = false
      + service_plan     = "5ed9f319-4c75-4851-9885-598a96b7febc"
      + space            = "e1fb8eaa-a857-42f0-a46f-7c08da3dfbaa"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudfoundry_service_instance.database: Creating...
cloudfoundry_service_instance.database: Still creating... [10s elapsed]
cloudfoundry_service_instance.database: Still creating... [20s elapsed]
cloudfoundry_service_instance.database: Still creating... [30s elapsed]
cloudfoundry_service_instance.database: Still creating... [40s elapsed]
cloudfoundry_service_instance.database: Still creating... [50s elapsed]
cloudfoundry_service_instance.database: Still creating... [1m0s elapsed]
cloudfoundry_service_instance.database: Still creating... [1m10s elapsed]
cloudfoundry_service_instance.database: Still creating... [1m20s elapsed]
cloudfoundry_service_instance.database: Still creating... [1m30s elapsed]
cloudfoundry_service_instance.database: Still creating... [1m40s elapsed]
cloudfoundry_service_instance.database: Still creating... [1m50s elapsed]
cloudfoundry_service_instance.database: Still creating... [2m0s elapsed]
cloudfoundry_service_instance.database: Still creating... [2m10s elapsed]
cloudfoundry_service_instance.database: Still creating... [2m20s elapsed]
cloudfoundry_service_instance.database: Still creating... [2m30s elapsed]
cloudfoundry_service_instance.database: Still creating... [2m40s elapsed]
cloudfoundry_service_instance.database: Still creating... [2m50s elapsed]
cloudfoundry_service_instance.database: Still creating... [3m0s elapsed]
cloudfoundry_service_instance.database: Still creating... [3m10s elapsed]
cloudfoundry_service_instance.database: Still creating... [3m20s elapsed]
cloudfoundry_service_instance.database: Still creating... [3m30s elapsed]
cloudfoundry_service_instance.database: Still creating... [3m40s elapsed]
cloudfoundry_service_instance.database: Still creating... [3m50s elapsed]
cloudfoundry_service_instance.database: Still creating... [4m0s elapsed]
cloudfoundry_service_instance.database: Still creating... [4m10s elapsed]
cloudfoundry_service_instance.database: Still creating... [4m20s elapsed]
cloudfoundry_service_instance.database: Still creating... [4m30s elapsed]
cloudfoundry_service_instance.database: Still creating... [4m40s elapsed]
cloudfoundry_service_instance.database: Still creating... [4m50s elapsed]
cloudfoundry_service_instance.database: Still creating... [5m0s elapsed]
cloudfoundry_service_instance.database: Still creating... [5m10s elapsed]
cloudfoundry_service_instance.database: Still creating... [5m20s elapsed]
cloudfoundry_service_instance.database: Still creating... [5m30s elapsed]
cloudfoundry_service_instance.database: Still creating... [5m40s elapsed]
cloudfoundry_service_instance.database: Creation complete after 5m43s [id=2bcbcb23-9f3b-44f1-9b37-5d7554d02c3e]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
