### ISSUE TITLE
Document how to run migrations manually in deployed environments.

### ISSUE THREAD

**Issue by kryswisnaskas** [HHS/Head-Start-TTADP#232]
Enable running migrations manually in deployed and environments and document.

**Acceptance Criteria:**
- [ ] Developers are able to run migrations manually - forward and backward (undo) in the deployed environments.
- [ ] Steps are documented

**Comment by SarahJaine** [comment]
I'm not 100% sure what this ticket is speaking to as it is now 7 months later. Migrations in deployed environments are run by the CD pipeline. I can't think of scenario where we would want to run these migrations manually.
@kryswisnaskas If this is still a priority please write as a new ticket in Jira.
