### ISSUE TITLE
Download of Uploaded Documents

### ISSUE THREAD

**Issue by marriej** [HHS/Head-Start-TTADP#247]
As a user I need to be able to download files attached to an AR to my computer.

**Acceptance Criteria:**
- User can click to download
- File is available for download after it passes the security scan

Link to the design:
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/135594749

**Exclusion:**
- Ability to download multiple files at the same time

**Comment by dcmcand** [comment]
If the clamav instance is unavailable, do we still not allow downloads? or just mark it as potentially unsafe and allow downloading anyway?
