### ISSUE TITLE
Setup section in README.md does not mention AUTH_CLIENT_ID or AUTH_CLIENT_SECRET

### ISSUE THREAD

**Issue by dcmcand** [HHS/Head-Start-TTADP#249]
The setup instructions in README.md do not specify that you need to update the `AUTH_CLIENT_ID` or `AUTH_CLIENT_SECRET` variables when you copy `.env.example` to `.env`. 

This should be added as well as information about where to obtain those values.

**Comment by rahearn** [comment]
The fix for this was merged in #248
