### ISSUE TITLE
As a user, I want to be redirected after submitting my activity report so I can continue my work

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#266]
As a user, I want to be redirected after submitting my activity report so I can continue my work.

Acceptance Criteria:

- [ ] User is returned to their landing page (list of reports).
- [ ] Success message displayed on landing page. "Your report was successfully submitted"
- [ ] Message has close button "x"

**Link to design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/137152191

**Comment by arickalewis1** [comment]
I am having issues with UXPin and Sketch. I'm sharing the design as an image here and will upload the link as soon as I can get it working again. @gopar @marriej 

![AR - Successfully submitted](https://user-images.githubusercontent.com/54509359/108878086-7fea4a00-75c5-11eb-966c-c8fef64d5088.png)

**Comment by gopar** [comment]
Should this also be the case for reviewing/approving reports @rahearn ?

**Comment by rahearn** [comment]
> Should this also be the case for reviewing/approving reports

Yes, probably. @PatricePascual-ACF what do you think?

**Comment by PatricePascual-ACF** [comment]
@gopar yes, if this is an easy add, users will appreciate it!
