### ISSUE TITLE
Button update

### ISSUE THREAD

**Issue by marriej** [HHS/Head-Start-TTADP#268]
Task: Change/Update the bottom CTA buttons in the form as instructed below:

Activity summary: "Back" "Save" "Save & Continue"
Topics and Resources: "Back" "Save" "Save & Continue"
Goals and objectives: "Back" "Save" "Save & Continue"
Next Steps: "Back" "Save" "Save & Continue"
Review and Submit:  "Save Draft" and "Submit for approval"

**Comment by PatricePascual-ACF** [comment]
@arickalewis1 +@marriej
I can envision user confusion over "Save" being named worded twice. 
Is this OK? 

Activity summary: "Back" "Save" "Nex Page"
Topics and Resources: "Back" "Save" "Next Page"
Goals and objectives: "Back" "Save" "Next Page"
Next Steps: "Back" "Save" "Next Page"
Review and Submit: "Save Draft" and "Submit for approval"

**Comment by arickalewis1** [comment]
@PatricePascual-ACF @marriej is there any way we could test out what we have during our last bit of testing? Then if there's confusion we can change the wording before launch.

**Comment by PatricePascual-ACF** [comment]
@arickalewis1 Sure -or could we do it during next week's D&D? 
Since it's a small thing, could real-time votes be enough?

**Comment by arickalewis1** [comment]
True! Let's discuss in our D&D planning tomorrow. @PatricePascual-ACF

**Comment by arickalewis1** [comment]
<img width="279" alt="Screen Shot 2021-01-27 at 1 35 05 PM" src="https://user-images.githubusercontent.com/54509359/106043771-7c39d500-60a4-11eb-88bd-5cfd756f8bcf.png">

**Comment by arickalewis1** [comment]
<img width="270" alt="Screen Shot 2021-01-27 at 1 35 51 PM" src="https://user-images.githubusercontent.com/54509359/106043858-95db1c80-60a4-11eb-9252-d99be67a4263.png">
