### ISSUE TITLE
Create System Maintenance Page

### ISSUE THREAD

**Issue by marriej** [HHS/Head-Start-TTADP#302]
Maintenance page in place.
For SmartHub, we could implement a basic maintenance page with a message notifying the user that the site is currently down. It would then be used if there is either maintenance needed or we need to take the site offline for any reason.

Acceptance Criteria:

- [x]  Frontend page created

- [x] Document how to put up and down the maintenance page

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/137277403

Due: 3/16/21
Launch Plan: https://docs.google.com/spreadsheets/d/1yJH1-rYc0R1LQ34U6IoKVBGX68BzH2vZRQjBaX6J7Ts/edit#gid=312021752

**Comment by rahearn** [comment]
I'm not sure cloud.gov offers something like this. What did you have in mind?

**Comment by kryswisnaskas** [comment]
Doesn't look like cloud.gov offers anything. However, they have ways to create their own status and maintenance pages - in case it is needed for their site.

For SmartHub, we could implement a basic maintenance page with a message notifying the user that the site is currently down. It would then be used if there is either maintenance needed or we need to take the site offline for any reason.

Acceptance Criteria:
- [ ] Frontend page created
- [ ] Document how to put up and down the maintenance page

**Comment by dcmcand** [comment]
@rahearn I am thinking this could just be a static html site that we can point the load balancer to if we need to take the app down for maintenance. It looks like cloud.gov offers static hosting. Can you confirm that and the fact that we can point to LB to the static site instead of the app in case of maintenance? Is that something that @kryswisnaskas or @jasalisbury could do if you aren't available?

**Comment by rahearn** [comment]
> It looks like cloud.gov offers static hosting

AFAIK, there is a static buildpack, but I think routing traffic to it would involve a full app deploy with the new buildpack. We don't have direct access to the LB to just point it to a different backend while the first remains up.

I am following up with cloud.gov support to see if they support basically the equivalent of `heroku maintenance:on`

**Comment by dcmcand** [comment]
@rahearn Any follow up on this? If we can't change the LB could we do it in DNS of cloud.gov doesn't have a built in?

**Comment by dcmcand** [comment]
It looks like we could remap the route within cloud.gov to another app, so if we deploy the maintenance page as a static buildpack, if we need to take the site down we could just do that through the cloud.gov portal. Is that accurate?

**Comment by rahearn** [comment]
> Is that accurate?

Yes, sorry this hasn't been the top of my list, but I believe this is the best way for us to go.

**Comment by dcmcand** [comment]
Ok, so my current plan is:
1. Build a static HTML page to a design provided by @arickalewis1 
2. Add it to `manifest.yml` using  [Static File Buildpack](https://docs.cloudfoundry.org/buildpacks/staticfile/index.html)
3. Create a bash script to put the site in maintenance mode .

The script will remap the application route to the static  site and add a maintenance route so we can still access the app. Then we are done, it can swap the route back.
 Does anyone see any issues with this approach? @rahearn @kryswisnaskas @dcloud @jasalisbury @gopar

**Comment by rahearn** [comment]
Sounds good, some thoughts:

Are you thinking that the static buildpack will just always be running? Or we'd push it up when needed? If the latter then it should be added to an additional manifest file that we can `cf push -f 'new.file.yml'` when needed. If the former, then adding it to the main manifest makes sense.

The routing could maybe be simpler, though I'm not sure. I'm pretty sure our app will have the `tta-smarthub-prod.app.cloud.gov` route in addition to `ttahub.ohs.acf.hhs.gov`. If the maintenance page has `tta-smarthub-maint.app.cloud.gov` (or whatever) then maybe we can just switch which app `ttahub.ohs.acf.hhs.gov` is routed to. Then we'll still have `tta-smarthub-prod.app.cloud.gov` for our use

**Comment by arickalewis1** [comment]
@dcmcand updated with link to design
