### ISSUE TITLE
QA: Resources field addition

### ISSUE THREAD

**Issue by PatricePascual-ACF** [HHS/Head-Start-TTADP#308]
As a user, I want a text box to to enter the URL of non-OHS resources. 

This section: https://tta-smarthub-staging.app.cloud.gov/activity-reports/1/topics-resources
This field: Resources 

@arickalewis1, I know you were addressig this already; it'd be great if we can follow language from the SmartSheet form. Thanks!   
[Resources section.docx](https://github.com/HHS/Head-Start-TTADP/files/6011332/Resources.section.docx)

**Link to design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880469

**Comment by arickalewis1** [comment]
I'm having issues with Sketch/UXPin, so here is the design until I can update with link. 
![AR - Topics - Empty with dropdown](https://user-images.githubusercontent.com/54509359/108877854-4285bc80-75c5-11eb-89f7-e18594b1bb75.png)

**Comment by jasalisbury** [comment]
This is being added in [this PR](https://github.com/adhocteam/Head-Start-TTADP/pull/205)
