### ISSUE TITLE
QA: Prompt to complete fields in "Topic and Resources" section

### ISSUE THREAD

**Issue by PatricePascual-ACF** [HHS/Head-Start-TTADP#309]
This page: https://tta-smarthub-staging.app.cloud.gov/activity-reports/1/topics-resources

The "Continue" button at bottom would not display until I added an ECLKC resource. 
Should there be a reminder message for fields that need to be completed?

**Comment by marriej** [comment]
Will be handled by upcoming validation PR. #314

**Comment by jasalisbury** [comment]
I'm pretty sure this has been addressed, but could you confirm @PatricePascual-ACF?

**Comment by rahearn** [comment]
Closing, this has been addressed already.
