### ISSUE TITLE
AR Review: On smaller screens, adjust layout to stack label/values

### ISSUE THREAD

**Issue by dcloud** [HHS/Head-Start-TTADP#318]
At smaller screen dimensions (e.g. 1024x768 and smaller), the row-layout of the Activity Report review page becomes cramped and hard to read. We improve on this by adjusting the layout from label-values on the same row to instead stacking the label and value as a column. We will also adjust spacing and typography so it is still clear what is a label versus a value, and the difference between one label-value pair and the next.

**Comment by rahearn** [comment]
Closed by #331
