### ISSUE TITLE
DB Reset tasks for sandbox and dev aren't working

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#330]
They both fail. Are they bringing value or should we just forward migrate them both?

**Comment by dcmcand** [comment]
Looks like migrations fail at 
```
19:49:16.769: [APP/TASK/Reset DB.0] == 20210215161922-add-statuses-to-file-model: reverting =======

19:49:16.779: [APP/TASK/Reset DB.0] ERROR: permission denied for table pg_enum

19:49:16.794: [APP/TASK/Reset DB.0] error Command failed with exit code 1.
```

**Comment by jasalisbury** [comment]
Undoing all the migrations was preventing issues where sandbox could miss a few migrations (or even have migrations applied that don't make it to the `main` branch). However we could probably forward migrate for now and just know if we run into any strange DB issues we may need to recreate the DB.

**Comment by rahearn** [comment]
FWIW, ssh into sandbox and dev and `sequelize db:migrate:undo --options-path .production.sequelizerc` will successfully one-step-at-a-time undo migrations to reset recent things if need be
