### ISSUE TITLE
Frontend updates to match design

### ISSUE THREAD

**Issue by arickalewis1** [HHS/Head-Start-TTADP#338]
**Left Nav**

- [x] Add user’s name above their email address
- [x] The page title should be bold: Activity Reports
- [x] Overall more spacing
- [x] `Logout` in the bottom should not be bold

**Activity Reports landing page**

- [x] Left margin spacing is a bit tight, can we increase it?
- [ ] Spacing between the two tables can be decreased

**AR form**

- [x] The `required` labels should be Source Sans Pro
- [x] Spacing of trashcan should move over to the right for the resources URL (16px padding)

**Comment by jasalisbury** [comment]
> Trashcan should appear next to the URL box for resources (it doesn’t show up until you add another resource)

If pressed with a single URL box should it be a no-op or remove the last text box?

**Comment by arickalewis1** [comment]
@jasalisbury I think the way it works now makes more sense... gonna delete that one.

**Comment by arickalewis1** [comment]
@jasalisbury just took at look in Sandbox. Looks good to me!
