### ISSUE TITLE
Add Monitoring Dashboard 

### ISSUE THREAD

**Issue by dcmcand** [HHS/Head-Start-TTADP#339]
As a user, I want a central monitoring dashboard to allow engineers to rapidly asses the health of the application. This dashboard should include key metrics such as [Google's four golden signals](https://sre.google/sre-book/monitoring-distributed-systems/#xref_monitoring_golden-signals).

Acceptance Criteria:
- [ ] Dashboard monitors latency, errors, saturation, and throughput
- [ ] Dashboard contains information necessary to respond to outages and security incidents

**Comment by rahearn** [comment]
Closing issue since it is in the "Done" column
