### ISSUE TITLE
Logs should be searchable

### ISSUE THREAD

**Issue by dcmcand** [HHS/Head-Start-TTADP#341]
As an engineer, I want production logs to be exported to an external service and to be searchable to help in troubleshooting production issues.

Acceptance Criteria:
- [ ] Logs are available through a service other than the application server
- [ ] Logs are searchable
- [ ] Logs are stored for a reasonable length of time

**Comment by dcmcand** [comment]
Cloud.gov provides log aggregation using an ELK stack available at https://logs.fr.cloud.gov/.

**Comment by rahearn** [comment]
@dcmcand this can be closed given the ELK stack, right?

**Comment by dcmcand** [comment]
@rahearn I was gonna leave it open until we had prod up. I want to set up a logs view that I can link to from the New Relic dash board that is just prod logs.

**Comment by rahearn** [comment]
Closing issue since it is in the "Done" column
