### ISSUE TITLE
Add Blue/Green Deployment for Production

### ISSUE THREAD

**Issue by dcmcand** [HHS/Head-Start-TTADP#348]
Adding blue/green deployments for production would give a measure of safety to future deploys by having a known good version running that we could rollback to.

This a deployment model that is supported by cloudfoundry (https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html).

One downside of this would be that you would not be able to add breaking migrations to the DB unless we want to copy the prod db for each deploy.

**Comment by rahearn** [comment]
Rather than blue/green, we'll likely want rolling deploys: https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html We're already on v7 of the cf-cli so it should be simple to do.
