### ISSUE TITLE
Ellipses buttons do not have accessible/meaningful names

### ISSUE THREAD

**Issue by iamjolly** [HHS/Head-Start-TTADP#351]
## Location
[Smart Hub Landing page](https://tta-smarthub-staging.app.cloud.gov/activity-reports)

## Issue description
The buttons in the last column of the second table on the page have ellipses as the only computed/available name. These need to be something more appropriate for users of assistive technology to better understand what will happen if the button is activated.

## Screenshots
![screenshot of buttons without accessible names](https://user-images.githubusercontent.com/1093423/110181426-01fa2000-7dc9-11eb-81fe-822299c2d08f.png)

**Comment by rahearn** [comment]
This was addressed already as part of https://github.com/HHS/Head-Start-TTADP/pull/352
