### ISSUE TITLE
Add pagination to "My Alerts"

### ISSUE THREAD

**Issue by kryswisnaskas** [HHS/Head-Start-TTADP#369]
Add pagination to my activity reports alerts. 

There is a `sequelize `bug that prevents successfully querying using `limit `and `order`. This ticket is to figure out if there is a workaround or another way of implementing pagination that works with sorting.

More information about the bug:
https://github.com/sequelize/sequelize/issues/9869

**Comment by awaner2** [comment]
Opened in Jira. Closing because we don't need the report in github.
