### ISSUE TITLE
Spike: Enable use of Grantee Name and Grant ID in Activity Reports

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#38]
**User Story 1:** As a TTA specialist creating a new Activity Report, I want the form to pull pertinent grantee/activity data from HSES so that I can select it rather than having to enter it and risk entering the wrong data.

**Goals of the Spike:**

1. Figure out how the Smart Hub can call HSES (or an intermediating API or other system) and get the following pieces of data for all active/current grants:

     - Grantee Name 
     - Grant ID 
     - Region for each grant
     - Any additional information about the Grantee or Grant that is available in HSES (program director, contact info, etc.)
2. Figure out what it will take to organize our data around Grantee rather than Grant. HSES doesn't organize the data this way, so we may have to come up with our way.
3. Document implementation decision and any implications for the design
4. Communicate the implications to the product, design, and research team members

**Exclusions:**
- UI and design - This spike is a "hello world app" kind of story to get us ready to implement the actual, user-facing story that uses this capability.
     - in particular, the design for how users are helped so that they know which Grant ID to pick

**Comment by kryswisnaskas** [comment]
Investigated data returned from ECKLC api. There is a lot of useful data there, but found some inconsistencies, for example a grantee with multiple grant ids doesn't show all of the grant ids that are returned when accessing a different endpoint. In general, there are multiple fields returned and the structure looks like the following:

```
{
      "addressLineOne": "153 Summer Street",
      "addressLineTwo": "",
      "pid": "10107",
      "grantNumber": "01HP000213",
      "delegateNumber": "200",
      "type": 2,
      "region": 1,
      "name": "Childrens Friend and Service",
      "granteeName": "Children's Friend And Service",
      "city": "Providence",
      "state": "RI",
      "zipFive": "02903",
      "zipFour": "4011",
      "phone": "(401)276-4300",
      "registrationPhone": "(401)752-7575",
      "fax": "(401)861-0507",
      "email": "sdelvicario@cfsri.org",
      "website": "http://www.childrensfriendri.org",
      "identifier": "childrens_friend_and_service_ri",
      "county": "Providence County"
    }
```

**Comment by kryswisnaskas** [comment]
Grantee types:

1. Head Start Center
2. Early Head Start Centers
3. Migrant and Seasonal Head Start Center
4. Migrant and Seasonal Early Head Start Center
5. American Indian and Alaskan Native Head Start Center
6. American Indian and Alaskan Native Early Head Start Center

**Comment by kryswisnaskas** [comment]
- types 1,2 are mostly all in regions 1-10
- types 3,4 are mostly all (except 2) in region 12
- types 5,6 are all in region 11
- Couple of unexpected results:
- There is one grantee in region 11 marked as type 1. Wonder if it's a mistake. It's Bristol Bay Native Association from AK.
- There are 34 grantees of type 1,2 that show region 13
- There are 2 grantees of type 3,4 also with region 13

The API flags region 13 as an invalid region if trying to directly access the programs from it.

**Comment by kryswisnaskas** [comment]
Met with HSES and as a result the plan is to use their data directly, likely from a file.

**Comment by PatricePascual-ACF** [comment]
Hi, @kryswisnaskas + @rahearn - we may need to get this info directly from HSES? 
HSICC's "type" labels (for their publicly accessible center locator) are slightly different than TTA. 
-It's missing EHS-CCP grants (a funded combo of EHS and Child Care services) 
-We wouldn't use "Center"
Krys, your Reg 11/type 1 does look like a mistake. Should we tell Uira in case it's on the HSES side?

**Comment by pamlo412** [comment]
Discussed with team: the ECKLC "type" is different than what's in HSES. We don't want to use the ECKLC type, just the HSES.

**Comment by pamlo412** [comment]
Closing this spike.
