### ISSUE TITLE
Spike: Admin tool for managing roles and permissions

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#39]
**User story:** As a Smart Hub admin, I want a simple tool for managing roles and permissions so that I can ensure all TTA team members have the access they need.

**Goals of this spike:**
- Investigate roles and permissions in HSES
- Figure out a phase 1 way of managing them in Smart Hub. Note that the first admins will be Ryan and possibly Krys (as the only two team members with prod access). In a later phase, we may build a more user-friendly tool for use by OHS staff.
- Document any critical architectural or implementation decisions
- Communicate the plan to the product lead so she can create any needed followup stories in the backlog.

**Comment by pamlo412** [comment]
Adding this story to sprint 0 for Josh to take a look at. It was intended for sprint 1 and may carry over into that sprint.

**Comment by pamlo412** [comment]
Moving this story to sprint 1 for completion.

**Comment by jasalisbury** [comment]
@pamlo412 The admin UI portion is mostly done, at least the UI part of it. There will be some more work to do on it once we nail down some more specifics on permissions. We will need tickets for the following:

 1. Implement Permissions on the backend. This includes the database schema and API endpoints. Will need to come to a consensus on how we want permissions to work. I would suggest separating each capability from the regions and having permissions be the combination of a region and capability. An example of a permission would be `READ_REPORTS` (the capability) on region 1. Some capabilities would be "regionless" (like the `ADMIN` capability). The admin UI as currently built assumes this is the path we will take but it could easily be changed.
 2. Update the UI to handle any new or updated permission/user schema (the first issue in this list). Also update the UI to actually fetch data from the API and call the API when saving/creating users.
 3. Determine which capabilities we need to define. Some possibilities:
 * ADMIN - Can edit users with the admin UI
 * SITE_ACCESS - Can view the TTAHUB site
 * READ_REPORTS - Can view activity reports for the region
 * READ_WRITE_REPORTS - Can view and update/create activity reports for the region

**Comment by pamlo412** [comment]
@jasalisbury I created #50, #51, and #52 for the follow-up spikes/stories for this spike. We'll review them at grooming tomorrow.
