### ISSUE TITLE
Include full patch version for node.js

### ISSUE THREAD

**Issue by kryswisnaskas** [HHS/Head-Start-TTADP#44]
Modify the existing version of node.js to include the full patch, e.g. 12.18.4

**Acceptance Criteria**
Fun patch version is included and CircleCI build passes.

**Comment by SarahJaine** [comment]
Where is this issue proposing this patch version specification be introduced? Node versions are specified in several places: package.json, the docker image/docker executor in circle ci, and in the docker file.

**Comment by rahearn** [comment]
Yes, all of those.

1) package.json to ensure we're getting security fixes that we expect in deployed environments
2) circleci config to ensure we're testing against the same version as is running in production
3) Dockerfile for consistency with the first two, though I suppose this is the least important, especially if package.json will ensure that we get the expected patch level.

**Comment by SarahJaine** [comment]
@rahearn Great, that's exactly the response I was looking for. (That Q was my soft way of saying, we really shouldn't do this in one place if we're not going to do it in all places.) 🙂
