### ISSUE TITLE
Spike: Define permissions 

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#51]
This spike is to define the specific permissions we will allow admin users to set for end users of the Smart Hub.

**Goals of this spike:** 
- Confer with 18F tech lead, Ad Hoc product lead, and OHS product owner to determine the permissions we need to offer in the Smart Hub
- document the decisions and definitions in the comments to this issue
- advise product lead on changes needed to #52  as a result of this spike

**Dev notes:**
Starting place for discussion is these possible permission categories: 

- ADMIN - Can edit users with the admin UI
- APPROVE_REPORTS
- READ_REPORTS - Can view activity reports for the region
- READ_WRITE_REPORTS - Can view and update/create activity reports for the region

**Comment by rahearn** [comment]
Is this a spike, or just a placeholder for a meeting between some of us to review the results of #39 and agree on the first set of permissions to implement as part of #52? I want us to be mindful that we won't have the full set of permissions needed for the system, or even the MVP, and that's ok.

**Comment by pamlo412** [comment]
@rahearn - this issue is a spike representing a dependency: we want the initial permissions to be agreed upon before we begin work on #50. It probably would be best handled via a meeting. To my thinking, that doesn't mean it's not a spike.

I'm surprised to hear you say we can't decide yet on the full set of permissions for the MVP. I definitely want to be part of the meeting in which we figure out what's possible, so I understand any constraints necessitating more permissions work, beyond this setup story, for the MVP.

**Comment by pamlo412** [comment]
Discussed this issue at standup today and agreed that we can start with the above list of permissions. I updated #50 and am closing this spike.
