### ISSUE TITLE
Spike: Determine how to set up BDD testing

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#56]
BDD testing has been requested/recommended by 18F as a good way to satisfy OCIO stagegate requirements to provide test scripts for their review, because BDD test scripts are human-readable so we don't have to provide ancillary documentation to help OCIO understand the scripts. Our tech lead can quickly complete the stagegate documentation by providing a link to the test scripts as we build them. Then OCIO can review them as and when they wish.

Goals of this spike:
- evaluate [cucumber](https://cucumber.io/) as the recommended tool to use for this purpose
- document what's needed to get it up and running
- test drive it using one of our early stories
- confer with team about the LOE of setup and the ongoing LOE of making this part of our definition of done
- if cucumber poses too many risks/issues (in the dev team's view), consider alternatives for BDD testing and alternatives for meeting the OCIO stagegate requirement
- make a recommendation to the tech and product leads

**Comment by kryswisnaskas** [comment]
Evaluated cucumber-js, which is a tool for running tests and presenting results in a plain language. The actual test implementation can be accomplished in various ways. For this spike, looked at selenium webdriver and puppeteer. Selenium webdriver is a framework for browser testing.

> Puppeteer is a Node library which provides a high-level API to control Chrome or Chromium over the DevTools Protocol. Puppeteer runs headless by default, but can be configured to run full (non-headless) Chrome or Chromium.

Puppeteer allows an easier integration with CI. I was able to test drive cucumber-js with puppeteer and circleCI. Currently, by default, cucumber shows short lived, publicly available output reports that self destruct within 24 hours. Future plans are to include the reports in github repository, but timeframe for this feature is unknown.

Following is an example of such a report. Note that in addition to test output, a commit associated with the tests is also included:

![image](https://user-images.githubusercontent.com/28231976/95632690-39e87b80-0a54-11eb-9687-e567314972a6.png)

**Comment by kryswisnaskas** [comment]
Other option is to use a different mechanism. Evaluated adding a library `cucumber-html-reporter` that allows generating html reports. This integrates with CI well and the report could be available in CircleCI under the artifacts tab. Following is an example of a basic report:

![image](https://user-images.githubusercontent.com/28231976/95633179-212c9580-0a55-11eb-9ba1-d55343aff636.png)

**Comment by kryswisnaskas** [comment]
There are more configuration options that could be used both with the reporting library and cucumber as well as puppeteer.

Pros of using cucumber-js:
- provides visible and understandable tests output for all stakeholders
- potentially is useful for security compliance

Cons:
- adds time to story development to create and maintain test cases

**Comment by pamlo412** [comment]
@kryswisnaskas I know the sprint isn't quite over yet, so you have time still to formulate your recommendation about which way we should go; but I'm going to ask now anyway: are are you leaning towards Selenium+Puppeteer, cucumber-html-reporter, or continued research? (Her's hoping it's not continued research!) Also, did you get a more precise sense of how much time this will add to story development: so much that we need to treat this work via separate stories or small enough that we just need to allow for higher points on stories to accommodate?

**Comment by pamlo412** [comment]
Per standup, @rahearn has reviewed this spike and doesn't have any issues or questions. Closing this issue.
