### ISSUE TITLE
Add Design to Login page

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#67]
**User story:** As a TTA Smart Hub user, I want a login page that welcomes me to the Smart Hub with some helpful content and a login option, so that I know where get started working in Smart Hub.

**Acceptance Criteria:**
TBD, but to include:

**Design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134937340

- font and page design tweaks per @arickalewis1 
- content tweaks per @PatricePascual-ACF

**Comment by dcloud** [comment]
Per #139, there will be a link to a SmartSheet form to request permissions, rather than an email address.
