### ISSUE TITLE
Make frontend support IE 11

### ISSUE THREAD

**Issue by jasalisbury** [HHS/Head-Start-TTADP#71]
**User Story:**

As a user of the TTA Smart Hub, I want to be able to use Internet Explorer (IE) 11 to view the site, because it may be the only browser I can use.

[Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is not supported in IE. The frontend currently uses `fetch` to make calls against the API. This means users that use IE will not be able to use the TTA Smart Hub. We will need to do one of two things:
 1) Use [Axios](https://www.npmjs.com/package/axios). This is preffered as it matches the HTTP client library used in the backend
 2) Add a shim for `fetch`

**Acceptance Criteria:**

 - [ ] Axios or a shim is used to make API requests
 - [ ] Tests that use `fetch` are updated

**Comment by rahearn** [comment]
@jasalisbury IE11 testing VM should be available here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by rahearn** [comment]
Closed by #178
