### ISSUE TITLE
Duplicate Implement backend error handler

### ISSUE THREAD

**Issue by kryswisnaskas** [HHS/Head-Start-TTADP#80]
Implement an error handler on the backend
Implement a custom error handler, so that error handling on the backend is optimized, e.g. code doesn't need to be repeated in multiple places. Add logging of the request errors to the database.

**Comment by rahearn** [comment]
@kryswisnaskas did the work done on https://github.com/HHS/Head-Start-TTADP/issues/134 satisfy this story as well?

**Comment by kryswisnaskas** [comment]
@rahearn Correct. This can be closed
