### ISSUE TITLE
Step 1 of Activity Report creation

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#81]
**User story:**
As a TTA specialist creating an activity report, I want a quick and easy way to enter the initial facts about a TTA activity I've completed so that I can save them and come back later to complete the full report.

**Acceptance criteria:**
- After logging in to the TTA Smart Hub at https://tta-smarthub-dev.app.cloud.gov/, click the Activity Reports tab header to access step 1 of the Activity Report. 
     - Note: This is not how users will normally access the activity report. We are accessing it this way because we don't as yet have any content on the landing page, such as a button to create a new AR report, which will be added by #6.

- Identify who the activity was for:
     - select using these labels: Grantee Name(s) or Non-Grantee(s) 
     - if "Grantee Name(s)", many can be chosen. The options are Grantee Name 1, Grantee Name 2, and Grantee 3 (see Exclusions for future work to populate the grantees here)

- **Identify: “For multiple grantees: choose Cluster (single event) or Community of Practice (recurring)”**

- if Non-Grantee(s) **the options are:** 
CCDF / Child Care Administrator
Head Start Collaboration Office
QRIS System
Regional Head Start Association
Regional TTA/Other Specialists
State CCR&R
State Early Learning Standards
State Education System
State Health System
State Head Start Association
State Professional Development / Continuing Education

- Identify "Other Specialist(s) involved in this activity"
     - select from a list of current TTA Smart Hub users (i.e. us on the team. See Exclusions for future work to populate and possibly filter this list)

- **Identify, for this activity: "Start Date and End Date"** 

- **Identify "TTA duration (in hours)"**

- Identify "What services were provided?":
      - Training
      - Technical assistance
      - Both

**- Identify "How was TTA provided?":**
     - In-person
     - Virtual
     - Email
     - Telephone

- Identify "Grantee participant(s) involved": 
     - CEO / CFO / Executive
     - Center Director / Site Director
     - Coach / Trainer
     - Direct Service / Front line / Home Visitors
     - Family Chlid Care
     - Governing Body / Tribal Council / Policy Council
     - Head Start Program Director
     - Manager / Coordinator / Specialist / Case Manager
     - Program Support / Administrative Assistant
     - Teacher / Infant-Toddler Caregiver
     - Parent / Family / Guardian
     - Volunteer

- ** Identify the "Number of grantee participants involved"** 

 
**Design:**
This is where the design lives, but it needs updates to align with the above requirements from @PatricePascual-ACF 
[UXPin design](https://preview.uxpin.com/393c11017d9f5c4b174988a3e202b13395535651#/pages/133181339/simulate/sitemap)

**Exclusions:**
- pulling the options for dropdowns from the Smart Hub database: this UI coded options implemented for this story will be replaced by work done for #90
- pulling the grantee name and grant ID data from HSES in real time - the dev plan is to implement a regular pull of grantee names and grant IDs from HSES into our database so that the information is available to our users from our DB. This will be implemented via #88 .
- pulling specialist names into the list of collaborators. To be handled via #90.
- help selecting the right grant ID - users will need to know the grant IDs (user research may lead us to a different approach in the future)
- saving the report (to be handled by story #98):

**Comment by pamlo412** [comment]
As of today, we have an open PR about how we are going to get grantee name and grant ID from HSES. This new story is dependent on that story, #38 being completed.

**Comment by pamlo412** [comment]
@arickalewis1 @jasalisbury @kryswisnaskas - @PatricePascual-ACF will be adding fields to this story. The rule we agreed to was that we would exclude fields that blow out the scope of the story too much. So we're leaving Topics out even though we expect that field will be on this page. We'll finalize the list with her on Tuesday.

**Comment by rahearn** [comment]
One thing to think about here: I think for accessibility reasons the browser title should update not only on the "big" page changes (already implemented!) but for each step, and possibly even for each page within a step. Something like `Activity Reports - Step 1` or `Activity Reports - Activity Summary` with the second part indicating where in the process the user is.

**Comment by jasalisbury** [comment]
> One thing to think about here: I think for accessibility reasons the browser title should update not only on the "big" page changes (already implemented!) but for each step, and possibly even for each page within a step. Something like `Activity Reports - Step 1` or `Activity Reports - Activity Summary` with the second part indicating where in the process the user is.

Yeah I was looking at https://github.com/nfl/react-helmet to help managing the browser title, looks to be simple to implement

**Comment by PatricePascual-ACF** [comment]
@jasalisbury Hi. I made some updates based on Pat and Damon yesterday and marked them **in bold.** 
I also tried to make sure you had label names by "putting them in quotes."
Please lmk if anything is unclear. Thanks!
Source: https://docs.google.com/document/d/1pFhoBlRtl19TZb0cteUOGq8YaGw4GxXzx1pgvgWHTEk/edit#

**Comment by rahearn** [comment]
- [ ] The business and/or user value of a story has been met
- [ ] CI pipeline green
- [ ] Code is meaningfully tested
- [ ] No linting errors or warnings
- [ ] UI meets WCAG 2.1 - Levels A and AA
- [ ] Code has deployed to a staging environment
- [ ] Security scans have passed
- [ ] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions with [the Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md).
- [ ] Boundary and Data Flow Diagrams are updated when a change invalidates the current version.
- [ ] Logical Data Model Diagram is updated on DB schema changes.
- [ ] Public API methods are documented when added or changed.
- [ ] OSCAL templates are completed when security controls are implemented or modified.

**Comment by rahearn** [comment]
Closed via #120
