### ISSUE TITLE
Ability to display validation/error messages without trapping user

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#84]
As a user using assistive technologies who encounters an error of any sort when working in the Smart Hub, I want to be able to get the error and navigate away from it so that I am not stuck in this error with no way out.

Need to list out the possible errors and associated error messages. Need separate stories for front-end validation errors and server errors.

Front end errors:
URL not found - 404

Server messages:
any 5xx error - e.g. can't reach HSES to save an entry

Notes:
- We want design for this story before we pick it up.
- we may want to split this into 3 stories

**Comment by rahearn** [comment]
@pamlo412 I'm not sure this needs to be it's own story. Trapping users will result in an accessibility fail on any story that implements that error, so it will be dealt with in that story. Can we delete this?

**Comment by rahearn** [comment]
Closing this after confirming with team. Any issues with trapping errors will be dealt with on change that implements the trap.
