### ISSUE TITLE
Dev Chore/Task: Implement Cucumber tests for the basic stepper in the Activity Report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#91]
Following up on our # , the spike about cucumber testing, we will create cucumber test scripts for #53 .

**To be completed with this task:**
- Set up cucumber so it can run automatically in each environment.
- Run it against the stepper work completed in Sprint 1.
- Demo the test script to @rahearn and, if possible, someone on the OCIO team (for whom this work has the most value)

**Considerations:**
- we will need to add code to bypass the HSES login so we aren't hitting the live server

**Comment by rahearn** [comment]
The demo for someone on OCIO can be handled at either an IPT meeting, or the regular sprint demo.

**Comment by rahearn** [comment]
Merged in #115
