### ISSUE TITLE
Update frontend icons/meta tag

### ISSUE THREAD

**Issue by jasalisbury** [HHS/Head-Start-TTADP#93]
As a user of the TTA Smart Hub, I want to have distinct icons and correct meta tags, so the Smart Hub is easily identifiable when linked or bookmarked.

---

The icons used by the frontend (shown when bookmarking, in the address bar, etc...) are still the default create-react-app icons. We need to update these icons. Also the description meta tag still reads "Web site created using create-react-app", which we will also want to update.

## Prerequisites 

 1. A new icon is designed (192x192 and 512x512)
 2. Determine new site description

## Acceptance Criteria

 1. New icon used when linking/bookmarking the TTA Smart Hub
 2. New site description used in the appropriate `<meta />` tag

**Comment by dcloud** [comment]
Handling this at the same times as #86
