### ISSUE TITLE
CI: Improvements to OWASP ZAP

### ISSUE THREAD

**Issue by SarahJaine** [HHS/Head-Start-TTADP#95]
In PRs https://github.com/adhocteam/Head-Start-TTADP/pull/44 / https://github.com/HHS/Head-Start-TTADP/pull/94 ticket https://github.com/HHS/Head-Start-TTADP/issues/11 we added OWASP ZAP tot he CI pipeline. This issue is for additional improvements that were left out of the initial PR for the sake of expediency.

Tasks:
- [x] capture owasp zap report as CircleCI "artifact" or "test"
- [ ] create way for owasp zap baseline scan to run locally

**Comment by rahearn** [comment]
For running locally, it might make more sense to become familiar with the desktop app? https://www.zaproxy.org/getting-started/

It's definitely more flexible and will let you dig in deeper than the headless docker option.
