### ISSUE TITLE
Handle display and permissions for Region 13 grantees

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#96]
**User story:**
As a specialist working with a grantee who has been transitioned to Region 13/CDI and given a new grant number, I want to be able to select the name of the grantee with the new CDI grant number so that I'm accurately referencing the grantee and grant.

**Info on Region 13:**
See https://github.com/HHS/Head-Start-TTADP/wiki/Region-13

**Acceptance criteria:**
- [ ] when a grantee is moved into CDI/Region 13, the grant number for the CDI grant is what displays and can be selected in the grantee name and grant number field in the Activity Report.
 
**Notes:**
- CDI employees will not be TTA Smart Hub users.
- Non-CDI specialists who were working with a grantee before they entered CDI retain access to the grantee's information while the grantee is in Region 13. 
- grantees moved to CDI will have new grant numbers so we can mark the previous grant numbers inactive
- it's fine, per Damon, if the user continues to select the old grant number until we have the updated data with the CDI grant number
- CDI grant numbers are all prefixed with "90CH"

**Comment by pamlo412** [comment]
Per @PatricePascual-ACF in Slack: "Pat said last year CDI was 'outside' of our TTA and we didn't pursue it further.
A few weeks ago Ryan and Krys noted that the grantee gets a new grant number during CDI. (I get why, but it seems like a decision where TTA was not at the table.)"

**Comment by pamlo412** [comment]
Research from @PatricePascual-ACF : From Jesse Escobar, grants div.

**CDI**
-We can use HSES as the current "source of truth" for whether a grantee is under CDI.
-Roughly how many grantees are under CDI each year? This really fluctuates since the number of grants that compete are not split evenly across years. I would say it roughly ranges between 15-25. Right now we have about 26 active CDI grants, but I think this is on the high end given that we had a lot more grants in the two most recent DRS cohorts resulting in more competition and transition than is typical. 
-Does Grants Solutions or HSES have a conversion table to link the original and CDI grant numbers? GS does not track this.
HSES does track the "succeeding" and "preceding" grant of all grants including CDI grants, but it is difficult to rely on it when it is not a one-to-one exchange. For example, when only part of a CDI grant is awarded to a new provider. Additionally, I believe this is somewhat of a manual process so it is possible for it to not be fully updated. For example, one CDI grant absorbing two prior grants but only showing one preceding grant. This appears to have gotten better. 
- Do you think Regional TTA generally reports under that new number, or under the original grant number? If CDI is awarded a grant and fully resumes services, the prior grant is made inactive and the T/TA events should be logged in the CDI grant. Once the CDI grant ends and the service area fully transitions to a new provider/grant, then the new grant would have the T/TA events.
In neither case should an inactive grant (the preceding one) be used to log T/TA events.
 Grantees that cross geographic regions.
-Do you know how many grantees operate in more than one region?
There are agencies/grantees that have multiple grants which span more than one region. I believe there are 23 agencies out of the nearly 1,600 that have grants in more than one region. 
 -Are they typically in multiple regions, or just two?
Typically in two and it's typically Region 12 (Migrant) and one other region. Of the 23 agencies with grants in more than one region, 5 do not fit this description. 3 of those 5 have grants across three regions, none in Region 12. One has two grants, niether in Region 12. And the last one has four grants, none in Region 12. 
-Are they only in Regions 11 and 12, or do some super-grantees also cross regions?
See prior response. None of these agencies are in Region 11.

**Comment by pamlo412** [comment]
@PatricePascual-ACF Per @kryswisnaskas - our ability to do this story depends on getting an HSES API, for which we are still waiting. The ECKLC API we have doesn't support queries to identify Region 13 grantees/grants. Since we already have a large body of work for the MVP and we are now date driven, are you willing to reprioritize this work for completion after the MVP release? (I've added a Post MVP label so we can group any other candidates for descoping from the MVP.)

**Comment by PatricePascual-ACF** [comment]
> @PatricePascual-ACF Per @kryswisnaskas - our ability to do this story depends on getting an HSES API, for which we are still waiting. The ECKLC API we have doesn't support queries to identify Region 13 grantees/grants. Since we already have a large body of work for the MVP and we are now date driven, are you willing to reprioritize this work for completion after the MVP release? (I've added a Post MVP label so we can group any other candidates for descoping from the MVP.)

Hi. Right - yes, this a work-around for being unable to identify Reg. 13 grantees/grants in HSES. But this is something that users need. During the field-by-field review of the AR led by Aricka which included @jasalisbury I thought the solution was to have a CDI field where all of the region's grantee names were selectable. Not their grant numbers, because that's the data that has changed. Can we revisit that before removing from MVP?
So I'd like to return to that before we move it off MVP.

**Comment by pamlo412** [comment]
@PatricePascual-ACF - Ah, I get it. Thanks for the clarification. I've revised the story accordingly and relabeled it as included in the MVP.

**Comment by pamlo412** [comment]
Discussed at grooming. Need to resolve issue of how we are displaying grantee names and grant numbers (two fields vs one) before we will commit to this story's wording and point it. Plan is to discuss the design tomorrow after standup.

**Comment by pamlo412** [comment]
Per follow-up discussion at grooming today, we will display the grantee names and grant numbers in one field and we believe we can get the CDI grant numbers from HSES. This second point means this story is really just a sub-case of the user story in #88. So I've moved the requirements to that story and am closing this one.
