### ISSUE TITLE
Section 2 of Activity Reports (Topics and Resources)

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#99]
**User Story:**

**Acceptance Criteria:**
...
- In a field labelled "Topics"...
- In a field labelled "Enter the URL for ECLKC Resources Used", enter the URL
- In an additional field, enter any alternative (non-ECLKC) resources used.
- In a field labelled "???", attach/upload files representing administrative records (Sign-in sheets, agendas, etc.) in each of the following two ways:
     - drag and drop 
     - click "choose" link, navigate to a file, select it, and click the attach option
...

**Requirements/Considerations:**
- The topics in the Smart Sheet are predefined and selectable and will also be so in our Activity Report. However, the topics in the Smart Hub may be different based on requirements discussions under way. So consider what options we have if there are topics in the Smart Sheet that we don't have in the Smart Hub. 
- File types supported for attachments: JPG, PNG, PPT, PPTX, DOC, DOCX, DOCM, XSL, XSLM, XSLX, TXT, ODP
- File sizes supported for attachments: ??

**Exclusions:**
- support for attaching OpenDocument file types (ODT, ODF, ODP) - this support isn't needed for the MVP
- enhancement to SmartSheet's handling of resources field will be implemented via #102 
- backend capture of any metadata for the alternative (non-ECLKC) resources. Use of alternative resources is a real use case, but we don't know how prevalent it is or how data about it might be used. So doing anything more with this field is post MVP.

**Comment by PatricePascual-ACF** [comment]
User story:
As a TTA specialist creating an activity report, I want to enter the details of the TTA I provided so I can provide a transparent accouting of work that the grantee and I did together.

**Comment by pamlo412** [comment]
Content for this step: context, topics, goals, objectives, and narrative.

**Comment by pamlo412** [comment]
Section 2 was implemented via #140. Closing this story.
